M48
; DRILL file {KiCad 7.0.6} date Fri Sep  1 18:36:30 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-01T18:36:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X5.5Y-3.2
X5.5Y-3.3
X5.5Y-3.4
X5.5Y-3.5
X5.5Y-3.6
X5.5Y-3.7
X5.5Y-3.8
X6.3Y-3.2
X6.3Y-3.3
X6.3Y-3.4
X6.3Y-3.5
X6.3Y-3.6
X6.3Y-3.7
X6.3Y-3.8
T0
M30
